"""User update

Revision ID: ce05fe8bddf0
Revises: f6a7b8c9d0e1
Create Date: 2026-03-13 02:37:28.053313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce05fe8bddf0'
down_revision: Union[str, Sequence[str], None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column as nullable with a default value of False
    op.add_column('user', sa.Column('email_to_set', sa.Boolean(), nullable=True, server_default=sa.false()))
    # Set all existing rows to False
    op.execute('UPDATE "user" SET email_to_set = FALSE')
    # Alter the column to be non-nullable and remove the default
    op.alter_column('user', 'email_to_set', nullable=False, server_default=None)
    # Continue with the rest of the migration
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('user', 'pwd',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'email_to_set')
    # ### end Alembic commands ###
